name: My First Workflow

on: push   #[push,fork] we can use array for multiple values

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v6

        
        - name: List and Read file
          run: |
               echo "Hello, this is my first Github Actions Job"
               ls -ltra
               cat README.md
     
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "RUN MFS, Dragon never sleep so you shouldn't too" > dragon.txt
        

        # - name: List files
        #   run : ls

        # - name: Read file
        #   run : cat README.md