name: My First Workflow

on: push   #[push,fork] we can use array for multiple values

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v6

        
        - name: Welcome message
          run: echo "Hello, this is my first Github Actions Job"

        

        - name: List files
          run : ls

        - name: Read file
          run : cat README.md